### ISSUE TITLE
environment

### ISSUE THREAD

**Issue by Esrappelt** [ds-academy/TadGAN#1]
What is your environment, can you give a requirement.txt file?

**Comment by byouloh** [comment]
I ran this source on Google Colab.
Then, you don't need any packages to be installed.
But, there is an error at final cell, train.

**Comment by khorshidisamira** [comment]
I had the same problem and I fixed it by changing
pred = critic_x(interpolated, training=True)
to
pred = critic_x(interpolated[0], training=True)
And
pred = critic_z(interpolated, training=True)
to
pred = critic_z(interpolated[0], training=True)
Hopefully it helps you too!

**Comment by Esrappelt** [comment]
> I had the same problem and I fixed it by changing
> pred = critic_x(interpolated, training=True)
> to
> pred = critic_x(interpolated[0], training=True)
> And
> pred = critic_z(interpolated, training=True)
> to
> pred = critic_z(interpolated[0], training=True)
> Hopefully it helps you too!
