### ISSUE TITLE
Train Error

### ISSUE THREAD

**Issue by byouloh** [ds-academy/TadGAN#2]
Hi, Im a Korean too, but writing an issue in English.

When I ran your code in google colab, I got the error as following;

ValueError                                Traceback (most recent call last)
<ipython-input-30-78f8d0f2ab9d> in <module>()
     28             x = minibatch[j * batch_size: (j + 1) * batch_size]
     29             z = np.random.normal(size=(batch_size, latent_dim, 1))
---> 30             epoch_cx_loss.append(critic_x_train_on_batch(x, z, valid, fake, delta))
...

ValueError: in user code:

    <ipython-input-26-44815e824161>:9 critic_x_train_on_batch  *
        pred = critic_x(interpolated, training=True)

...

ValueError: Layer model_2 expects 1 input(s), but it received 2 input tensors. Inputs received: [<tf.Tensor 'model_4/Cast:0' shape=(64, 100, 1) dtype=float32>, <tf.Tensor 'model_4/model_1/sequential_1/activation/Tanh:0' shape=(64, 100, 1) dtype=float32>]

It tells me your model has to input only one but received 2 inputs.
When I googled this issue then I found
https://stackoverflow.com/questions/61586981/valueerror-layer-sequential-20-expects-1-inputs-but-it-received-2-input-tensor

But, I can't find the similar code 
"it helped me when I changed: validation_data=[X_val, y_val] into validation_data=(X_val, y_val)" in your code, or models.

Can you help me?

**Comment by khorshidisamira** [comment]
I had the same problem and I fixed it by changing 
 `pred = critic_x(interpolated, training=True)`
to 
 `pred = critic_x(interpolated[0], training=True)`
And 
            `pred = critic_z(interpolated, training=True)`
to 
          `  pred = critic_z(interpolated[0], training=True)`
Hopefully it helps you too!

**Comment by byouloh** [comment]
@khorshidisamira 
Thank you so much. Your solution works well^^
When I run this source in local machine, there is a gpu issue of  CuDNNLSTM in python 3.9.2 and an "Input 'filter' of 'Conv2D' Op has type float32 that does not match type float64 of argument 'input' " in python 3.7.10 version. But everything is OK on Google Colab.

PS: Change CuDNNLSTM into LSTM in python 3.9.2, and no problem!

Thanks again, Samira.
